spring:
  datasource:
    url: jdbc:mysql://${mysql-ip:localhost}:${mysql-port:3306}/test
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect